# -*- mode: python; -*-
import os
import subprocess
import sys
import shutil

print 'install openvswitch'
vpath = '#/third_party/openvswitch-2.6.0'

env = DefaultEnvironment()
env['ENV']['CFLAGS'] = '-DOPEN_CONTRAIL_CLIENT -g'

config_opts = '--prefix=' + str(Dir('#/build'))

if not sys.platform.startswith('freebsd'):
    cmd = ('(cd ' + Dir('.').abspath + '; ' + str(Dir(vpath)) +
           '/configure' + ' ' + config_opts + '; make clean; make; make install)')
else:
    cmd = ('(cd ' + Dir('.').abspath + '; ' + str(Dir(vpath)) +
           '/configure' + ' ' + config_opts + '; gmake clean; gmake; gmake install)')

libs = [str(File('#build/lib/libopenvswitch.a'))]

openvswitch = env.Command('config.status', str(Dir(vpath)), cmd)

env.SideEffect(libs, openvswitch)

def Symlink(target, source):
    parent = os.path.dirname(target[0].abspath)
    if not os.path.exists(parent):
        os.makedirs(parent)

    if not os.path.exists(target[0].abspath):
        os.symlink(source[0].abspath, target[0].abspath)

srcdir = Dir(vpath).abspath
destdir = Dir('#/build/include/openvswitch').abspath

if not os.path.exists(destdir + '/include'):
  print 'copying to inc' + destdir 
  shutil.copytree(srcdir+'/include', destdir+'/include')

if not os.path.exists(destdir + '/lib'):
  print 'copying to lib' + destdir 
  shutil.copytree(srcdir+'/include', destdir+'/lib')


print 'done installing openvswitch'