	cp    controller/src/base/test/addr_test_util.cc temporary/.
	cp    controller/src/base/test/task_test_util.cc temporary/.
	cp    controller/src/base/test/task_test_util.h temporary/.
	cp    controller/src/control-node/control_node.cc temporary/.
	cp    controller/src/io/test/event_manager_test.cc temporary/.
	cp    controller/src/ksync/ksync_object.cc temporary/.
	cp    controller/src/ksync/ksync_sock.cc temporary/.
	cp    controller/src/net/mac_address.h temporary/.
	cp    controller/src/schema/test/ifmap_identity_property_test.cc temporary/.
	cp    controller/src/schema/test/ifmap_link_attr_test.cc temporary/.
	cp    controller/src/vnsw/agent/oper/agent_profile.cc temporary/.
	cp    controller/src/vnsw/agent/port_ipc/test/test_port_ipc.cc temporary/.
	cp    controller/src/vnsw/agent/uve/vrouter_stats_collector.cc temporary/.
	cp    controller/src/vnsw/agent/vrouter/ksync/ksync_init.cc temporary/.
	cp    controller/src/xmpp/test/SConscript temporary/.
	cp    controller/src/xmpp/test/xmpp_client_standalone.cc temporary/.
	cp    controller/src/xmpp/test/xmpp_regex_test.cc temporary/.
	cp    tools/sandesh/library/cpp/sandesh.cc temporary/.
	cp    tools/sandesh/library/cpp/sandesh_client_sm.cc temporary/.
	cp    tools/sandesh/library/cpp/sandesh_client_sm_priv.h temporary/.
	cp    tools/sandesh/library/cpp/sandesh_session.cc temporary/.
	cp    windows/WindowsStubs/WindowsStubs/WindowsStubs.vcxproj temporary/.
	cp    windows/WindowsStubs/WindowsStubsTest/WindowsStubsTest.cpp temporary/.
	cp    windows/WindowsStubs/WindowsStubsTest/WindowsStubsTest.vcxproj temporary/.
