
#include "AgentConstants.h"
const std::string  AgentConstants::contrail_collector_log = "contrail-collector.log";
const std::string  AgentConstants::contrail_named_log = "contrail-named.log";
const std::string  AgentConstants::named_bind_log = "bind.log";
const std::string  AgentConstants::contrail_control_log = "contrail-control.log";
const std::string  AgentConstants::contrail_dns_log = "contrail-dns.log";
const std::string  AgentConstants::log_dns = "logdns";
const std::string  AgentConstants::contrail_query_engine_log = "contrail-query-engine.log";
const std::string  AgentConstants::contrail_vrouter2_log = "vrouter2.log";
const std::string  AgentConstants::contrail_collector_conf = "contrail-collector.conf";
const std::string  AgentConstants::contrail_keystone_auth_conf = "contrail-keystone-auth.conf";
const std::string  AgentConstants::contrail_ks_cert = "ks-cert";
const std::string  AgentConstants::contrail_ks_key = "ks-key";
const std::string  AgentConstants::contrail_ks_ca = "ks-ca";
const std::string  AgentConstants::contrail_database_conf = "contrail-database.conf";
const std::string  AgentConstants::contrail_control_conf = "contrail-control.conf";
const std::string  AgentConstants::contrail_ssl_certs_server_pem = "ssl_certs_server.pem";
const std::string  AgentConstants::contrail_ssl_server_privkey_pem = "server-privkey.pem";
const std::string  AgentConstants::contrail_ssl_certs_ca_cert_pem = "ca-cert.pem";
const std::string  AgentConstants::server_pem = "server.pem";
const std::string  AgentConstants::server_key = "server.key";
const std::string  AgentConstants::ca_cert_pem = "ca-cert.pem";
const std::string  AgentConstants::resolv_conf = "resolv.conf";
const std::string  AgentConstants::contrail_dns_conf = "contrail-dns.conf";
const std::string  AgentConstants::contrail_dns = "contraildns";
const std::string  AgentConstants::contrail_dns_named_log = "dns_named.log";
const std::string  AgentConstants::server_privkey_pem = "server-privkey.pem\n";
const std::string  AgentConstants::contrail_dns_test_dir = "dns_test";
const std::string  AgentConstants::contrail_query_engine_conf = "contrail-query-engine.conf";
const std::string  AgentConstants::temp_directory = "tmp/";
const  std::string AgentConstants::usr_directory = "usr/"; //usr/
const  std::string AgentConstants::var_directory = "var/"; //var/
const  std::string AgentConstants::bin_directory = "bin/"; //bin
const  std::string AgentConstants::log_directory = "log/"; //log/
const  std::string AgentConstants::etc_directory = "usr/"; //usr/
const  std::string AgentConstants::dev_directory = "dev/"; //dev/
