import os
# windows reference: http://www.boost.org/doc/libs/1_62_0/more/getting_started/windows.html
print "Building windows boost..."
boostpath = Dir('.').path + '\\..\\..\\..\\..\\third_party\\boost_1_62_0'
env = Environment(TARGET_ARCH='x86')
currentdir =  Dir('.').path
os.chdir(boostpath)

boost_libs = [
    'system', 'thread', 'date_time', 'regex', 'python', 'program_options',
    'filesystem', 'chrono'
]

# execute C:\contrail\windowsclean\windows\third_party\boost_1_62_0\bootstrap.bat

# execute b2 toolset=msvc-14.0 --build-type=complete  architecture=x86 address-model=32 stage --stagedir="C:\\contrail\\windowsclean\\windows\\build\\third_party\\boost_1_62_0"


