# -*- mode: python; -*-

# path to the sources
vpath = '#/third_party/curl-7.51.0'
print 'building curl'
env = DefaultEnvironment().Clone()

VariantDir(vpath + '/src', '#/' + Dir('.').path + '/src')

config_cmd = ('(cd ' + Dir('.').abspath + '; ' + str(Dir(vpath)) + ')')
print config_cmd
#config_products = [Dir('.').abspath + '/lib/curl_config.h', 'Makefile']

#curl_cfg = env.Command('config.status', File(vpath + '/configure'), config_cmd)


#libs = ['lib/.libs/libcurl.a']

#make_cmd = ('(cd ' + Dir('.').abspath + '; ' + 
#            'make clean; make; make install)')

#make_products = ['#/build/lib/libcurl.lib', '#/build/include/curl/curl.h']

#curl_make = env.Command(make_products, 'Makefile', make_cmd)


print 'done building curl'
