import subprocess
import os
import shutil

# -*- mode: python; -*-
print 'installing log4cplus'
vpath = '#/third_party/log4cplus-1.1.3-rc7'

env = DefaultEnvironment()
abs_vpath = Dir(vpath).abspath
abs_toppath = Dir('#').abspath

loglibs = [ str(File('#/build/lib/log4cplus.lib')) ]
logshlibs = [ str(File('#/build/lib/log4cplusD.dll')) ]
logproducts = loglibs + logshlibs #+ [ str(File('#/build/include/log4cplus/logger.h')) ]

def Symlink(target, source):
    print 'target =', target[0]
    print 'source = ' , source[0]
    parent = os.path.dirname(target[0].abspath)
    if not os.path.exists(parent):
        os.makedirs(parent)

    if not os.path.exists(target[0].abspath):
        os.symlink(source[0].abspath, target[0].abspath)

libpath = Dir(vpath).abspath
if not os.path.exists(libpath):
    print '%s not present' % libpath
    sys.exit(1)

def build_log4cplus_for_windows(target,source,env):
    cmd = 'xcopy ' + abs_toppath + '\controller\lib\log4cplus\msvc15\* ' + Dir(vpath).abspath + '\msvc10 /e /y'
    print cmd
    subprocess.call(cmd, shell=True)
    curdir = os.getcwd()
    os.chdir(Dir(vpath).abspath+ '\\msvc10')
    subprocess.call("msbuild log4cplus.sln", shell=True)
    cmd = 'xcopy /Y ' + Dir(vpath).abspath + r'\msvc10\win32\bin.Debug\*.lib ' + Dir('#/build/lib/*').abspath
    print cmd
    subprocess.call(cmd, shell=True)
    cmd = 'xcopy /Y ' + Dir(vpath).abspath + r'\msvc10\win32\bin.Debug\*.exe ' + Dir('#/build/bin/*').abspath
    print cmd
    subprocess.call(cmd, shell=True)
    cmd = 'xcopy /Y ' + Dir(vpath).abspath + r'\msvc10\win32\bin.Debug\*.dll ' + Dir('#/build/bin/*').abspath
    print cmd
    subprocess.call(cmd, shell=True)
    os.chdir(curdir)
    print os.getcwd()
    if not os.path.exists(Dir('#/build/lib').abspath+ r'\log4cplus.lib'):
      print 'copying log4cplus.lib'
      shutil.copyfile(abs_vpath +r'\msvc10\Win32\bin.Debug\log4CplusSD.lib', Dir('#/build/lib').abspath+ r'\log4cplus.lib')

srcdir = Dir(vpath + '/include/log4cplus').abspath
destdir = Dir('#/build/include/log4cplus').abspath

if not os.path.exists(destdir):
  print 'copying to ' + destdir
  shutil.copytree(srcdir, destdir)
  
env.Command('#/build/lib/log4cplus.lib', str(Dir(vpath)), build_log4cplus_for_windows)

#env.InstallAs( , vpath +r'\msvc10\Win32\bin.Debug\log4CplusSD.lib')
print 'done installing log4cplus'
