import subprocess
import os
# -*- mode: python; -*-
print 'installing log4cplus'
vpath = '#/third_party/log4cplus-1.1.3-rc7'

env = DefaultEnvironment()
abs_vpath = Dir(vpath).abspath
abs_toppath = Dir('#').abspath

loglibs = [ str(File('#/build/lib/liblog4cplus.lib')) ]
logshlibs = [ str(File('#/build/lib/log4cplusD.dll')) ]
logproducts = loglibs + logshlibs #+ [ str(File('#/build/include/log4cplus/logger.h')) ]

def build_log4cplus_for_windows(target,source,env):
    cmd = 'xcopy ' + abs_toppath + '\controller\lib\log4cplus\msvc15\* ' + Dir(vpath).abspath + '\msvc10 /e /y'
    print cmd
    subprocess.call(cmd, shell=True)
    curdir = os.getcwd()
    os.chdir(Dir(vpath).abspath+ '\\msvc10')
    subprocess.call("msbuild log4cplus.sln", shell=True)
    os.symlink(Dir(vpath + '/include/log4cplus').abspath, Dir('#/build/include/log4cplus').abspath)
#   cmd = 'copy ' +  abs_vpath + r'\include\log4cplus\logger.h ' +  abs_toppath + r'\build\include\log4cplus'
#   print cmd
#    subprocess.call(cmd, shell=True)
    os.chdir(curdir)

env.Command(logproducts, str(Dir(vpath)), build_log4cplus_for_windows)
Default(logproducts)
#env.SideEffect(products, log4cplus_copy)

#env.Alias('install', env.Install(env['INSTALL_LIB'], shlibs))

#env.Alias('install',  env.Symlink(env['INSTALL_LIB'] + '/liblog4cplus-1.1.3-rc7.dll' , env['INSTALL_LIB'] + '/liblog4cplus-1.1.3-rc7.dll'))

print 'done installing log4cplus'
#build log4cplus

