# -*- mode: python; -*-
import sys
print 'installing libxml2'
# path to the sources
vpath = '#/third_party/libxml2-2.7.8.win32'

env = DefaultEnvironment().Clone()

def libxml2_for_windows(target,source,env):
   cwd = os.getcwd()
   os.chdir(Dir(vpath).abspath)
   assert os.path.isdir(Dir(vpath).abspath)
   os.chdir(cwd)


env.InstallAs('#/build/lib/libxml2.lib', vpath + '/lib/libxml2_a.lib')

print 'done installing libxml2'