import os
import subprocess
import sys
import fnmatch

print 'Enter windowslib'



env = DefaultEnvironment().Clone()
env.AppendUnique(CCFLAGS='/DUNICODE')#both are needed by the compiler
env.AppendUnique(CCFLAGS='/D_UNICODE')

#vpath = '#/third_party/pugixml/src'
#env.VariantDir('#/' + Dir('.').path + '/src', vpath)
#pugixml_buildpath = Dir('.').abspath + '/src'

#lib = env.Library('pugixml', pugixml_buildpath + '/pugixml.cpp')

vpath = '#windows/src'
env.VariantDir('#/' + Dir('.').path + '/src', vpath,0)
windows_buildpath = Dir('.').abspath + '/src'

print windows_buildpath
files = Glob(windows_buildpath +'/*.cc')
libsources = ['#windows/src/agentconstants.cc','#windows/src/cpuinfo.cc','#windows/src/taskutil.cc', '#windows/src/timeutils.cc', '#windows/src/winnw.cc' , '#windows/src/wmi.cc']
windowsstubs_lib = env.Library('windowsstubs', files)
env.Install('#/build/lib/', 'windowsstubs.lib')
env.Alias('windowsstubs', '#/build/lib/windowsstubs.lib')
