# -*- mode: python; -*-

import os
import re
import subprocess
import sys
import glob
import shutil

print 'openssl enter...'

vpath = '#/third_party/openssl-1.0.2k'
buildpath = '#/build'

env = DefaultEnvironment()
ssllibpath = Dir(vpath).abspath+ r'\out32\ssleay32.lib'
cryptolibpath = Dir(vpath).abspath+ r'\out32\libeay32.lib'
opensslconfheader = '#build/include/openssl/conf.h'

def build_openssl_for_windows(target,source,env):
   cwd = os.getcwd()
   os.chdir(Dir(vpath).abspath)
   assert os.path.isdir(Dir(vpath).abspath)
   print os.getcwd()
   perlcmd = "perl Configure VC-WIN64A" + "--prefix=" + Dir('#/build')#incomplete
   subprocess.call("perl Configure VC-WIN64A ", shell=True)
   subprocess.call("ms\do_win64a", shell=True)
   subprocess.call("nmake -f ms\nt.mak", shell=True)
   subprocess.call("nmake -f ms\nt.mak install", shell=True)
   os.chdir(cwd)

env.Command([ssllibpath], str(Dir(vpath)) , build_openssl_for_windows)

#env.InstallAs('#build/lib/ssl.lib', ssllibpath)
#env.InstallAs('#build/lib/crypto.lib',cryptolibpath)

srcdir = Dir(vpath + '/inc32/openssl').abspath
destdir = Dir('#/build/include/openssl').abspath

if not os.path.exists(destdir):
  print 'copying files to' + destdir
  shutil.copytree(srcdir, destdir)

print 'openssl leave...'
     