# -*- mode: python; -*-
#
#Copyright (c) 2013 Juniper Networks, Inc. All rights reserved.
#

import sys
Import('DnsEnv')
env = DnsEnv.Clone()
env.Append(CPPPATH = '#third_party\OpenSSLWin32\include')
dns_mgr = env.Library('mgr',
                      ['dns_mgr.cc',
                       'dns_oper.cc',
                      ])
